group: travis_latest
language: python
cache: pip

matrix:
  include:
    - python: '2.6'
      env: MAKE_TARGET=test
    - python: '2.7'
      env: MAKE_TARGET=coverage-test
    - python: 'pypy'
      env: MAKE_TARGET=test
    - python: '3.3'
      env: MAKE_TARGET=test
    - python: '3.4'
      env: MAKE_TARGET=test
    - python: '3.5'
      env: MAKE_TARGET=test
    - python: '3.6'
      env: MAKE_TARGET=coverage-test
    - python: 'pypy3'
      env: MAKE_TARGET=test
    - python: 'nightly'
      env: MAKE_TARGET=test
  allow_failures:
    - python: 'nightly'
    - python: '2.6'

install:
  - if [ $MAKE_TARGET = coverage-test ]; then pip install coveralls; fi
  - git describe --tags --abbrev=4 || git pull --unshallow

script:
  - make $MAKE_TARGET

after_success:
  - if [ $MAKE_TARGET = coverage-test ]; then coveralls; fi
