dist: bionic
language: python
cache: pip

python:
  - "3.8"

before_install:
  - sudo apt-get -y install quilt

install:
  - python -m pip install coverage[toml] coveralls

before_script:
  - git describe --tags --abbrev=4 || git pull --unshallow --tags

script:
  - make -j2 coverage-test

after_success:
  - python -m coveralls
