[package]
name = "stgit"
version = "2.0.0-alpha.0"
edition = "2021"
authors = [
    "Catalin Marinas <catalin.marinas@gmail.com>",
    "Peter Grayson <pete@jpgrayson.net>",
]
license = "GPL-2.0-only"
homepage = "https://stacked-git.github.io/"
repository = "https://github.com/stacked-git/stgit"

[[bin]]
bench = false
path = "src/main.rs"
name = "stg"

[dependencies]
atty = "0.2"
chrono = "0.4"
git2 = "0.13"
indexmap = "1.7"
lazy_static = "~1.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
strsim = "0.10"
tempfile = "3"
termcolor = "1.1"
thiserror = "~1.0"

[dependencies.clap]
version = "3.0.0"
default-features = false
features = ["cargo", "color", "std", "suggestions", "wrap_help"]
