[tool.black]
line-length = 88
skip-string-normalization = true
target-version = ['py34']
include = '''
(
    \.pyi?$
)
'''
exclude = '''
(
    \/\..*$
  | \/cmdlist\.py
  | \/build$
  | \/dist
)
'''

[tool.coverage.run]
source = ['stgit']
branch = true
parallel = true

[tool.coverage.html]
title = 'StGit Coverage Report'
show_contexts = true
