name: CI

on:
  push:
    branches: ['*']
    tags: ['*']
  pull_request:
  schedule:
    # Every Sunday at 1:30
    - cron: '30 1 * * 0'

jobs:
  windows-build:
    name: Windows Build
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - name: Build
        run: |
          cargo --locked build --profile release
      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          install: diffutils make https://repo.msys2.org/msys/x86_64/msys2-runtime-3.4.9-3-x86_64.pkg.tar.zst
          path-type: inherit
      - name: Test
        shell: msys2 {0}
        env:
          STG_PROVE_OPTS: "--jobs=2"
          STG_TEST_OPTS: "--verbose-log"
          STG_PROFILE: "release"
        run: |
          timeout 900s make -C t SHELL_PATH=C:/msys64/usr/bin/bash prove
      - name: Show Failures
        if: ${{ failure() }}
        shell: msys2 {0}
        run: |
          make -C t show-failure-results
      - name: Install Wix Toolset v4
        run: |
          dotnet tool install --global wix --version 4.0.0
      - name: Install Wix UI Extension
        run: |
          wix extension add -g WixToolset.UI.wixext
      - name: Build MSI Installer
        shell: msys2 {0}
        run: |
          make -C contrib/wix
      - name: Upload MSI Package
        uses: actions/upload-artifact@v4
        with:
          name: stgit-msi-package
          path: contrib/wix/stgit-*.msi
