name: CI

on:
  push:
    branches: [ '*' ]
    tags: [ '*' ]
  pull_request:
  schedule:
  # Every Sunday at 1:30
  - cron: '30 1 * * 0'

jobs:
  build-and-test:
    name: Build and Test
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            profile: release
            toolchain: stable
          - os: ubuntu-latest
            profile: dev
            toolchain: stable
          - os: ubuntu-latest
            profile: dev
            toolchain: nightly
          - os: macos-latest
            profile: dev
            toolchain: stable
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Install Rust
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ matrix.toolchain }}
    - name: Build
      run: |
        cargo --locked build --all-features --profile ${{ matrix.profile }}
    - name: Install Test Dependencies (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install quilt gnupg2 libio-pty-perl
    - name: Install Test Dependencies (MacOS)
      if: matrix.os == 'macos-latest'
      run: |
        # coreutils provides the `timeout` command used to wrap `make` below.
        # gnu-sed is needed by some tests (e.g. t3400-pick.sh).
        brew install coreutils cpanminus gnu-sed
        echo "$(brew --prefix)/opt/gnu-sed/libexec/gnubin" >> $GITHUB_PATH
        echo "$(brew --prefix)/opt/coreutils/libexec/gnubin" >> $GITHUB_PATH
        sudo cpanm IO::Pty
    - name: Test
      env:
        STG_PROVE_OPTS: "--jobs=2"
        STG_TEST_OPTS: "--verbose-log"
        STG_PROFILE: ${{ matrix.profile }}
      run: |
        timeout 900s make -C t prove
    - name: Show Failures
      if: ${{ failure() }}
      run: |
        make -C t show-failure-results

  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Install Rust
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: stable
    - name: Run Unit Tests
      run: |
        cargo --locked test

  clippy:
    name: Clippy Lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Install Rust
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: stable
        components: clippy
    - name: Clippy Checks
      run: |
        cargo --locked clippy -- --deny warnings

  rustfmt:
    name: Format Lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Install Rust
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: stable
        components: rustfmt
    - name: Check formatting
      run: |
        cargo --locked fmt --all --check

  api-docs:
    name: API Documentation
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Install Rust
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: stable
    - name: Build docs
      run: |
        cargo rustdoc -- --deny warnings

  docs:
    name: User Documentation
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Install Rust
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: stable
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install asciidoc asciidoctor docbook-xsl-ns xmlto
    - name: Build Docs Asciidoc
      run: |
        make -j2 doc
    - name: Build Docs Asciidoctor
      run: |
        make -j2 USE_ASCIIDOCTOR=1 doc
    - name: Install HTML Docs
      run: |
        make -j2 USE_ASCIIDOCTOR=1 htmldir="$GITHUB_WORKSPACE"/stgit-html install-html
    - name: Upload HTML Docs
      uses: actions/upload-artifact@v3
      with:
        name: html-doc
        path: ${{ github.workspace }}/stgit-html

  packages:
    name: Prebuilt Packages
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Install Rust
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: stable
    - name: Install cargo-deb
      run: |
        cargo install cargo-deb
    - name: Install cargo-generate-rpm
      run: |
        cargo install cargo-generate-rpm
    - name: Build Packages
      run: |
        make deb rpm
    - name: Upload deb
      uses: actions/upload-artifact@v3
      with:
        name: stgit-deb
        path: target/debian/stgit_*.deb
    - name: Upload rpm
      uses: actions/upload-artifact@v3
      with:
        name: stgit-rpm
        path: target/generate-rpm/stgit-*.rpm

  windows-build:
    name: Windows Build
    runs-on: windows-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Install Rust
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: stable
    - name: Build
      run: |
        cargo --locked build --all-features --profile release
    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: UCRT64
        update: true
        install: diffutils make
        path-type: inherit
    - name: Test
      shell: msys2 {0}
      env:
        STG_PROVE_OPTS: "--jobs=2"
        STG_TEST_OPTS: "--verbose-log"
        STG_PROFILE: "release"
      run: |
        timeout 900s make -C t prove
    - name: Show Failures
      if: ${{ failure() }}
      shell: msys2 {0}
      run: |
        make -C t show-failure-results
